### ISSUE TITLE
Include DEA-bootstrapping

### ISSUE THREAD

**Issue by lse81** [Riksrevisjonen/pioneeR#6]
Include DEA-bootstrapping using rDEA-package.

**Comment by ohjakobsen** [comment]
Update UI in the following way: if a supported technology and direction is selected, show options to add confidence intervals to productivity estimation. In the table, add standard error, lower and upper bounds between efficiency score and slack.

**Comment by ohjakobsen** [comment]
@lse81 and @Aeilert: I hoped to create an exported function for the bootstrap, but since the bootstrap can take some time with a large _b_, I have settles against this. For each iteration of the bootstrap, we need to update the UI. This is not feasible from an exported function with the development time we have left for the moment. However, we should look into how we implement bootstrapping in pear and if it's possible to get information on progress in a Shiny session.
